baseURL = 'https://chemachin.es/'
languageCode = 'en-us'
title = 'Chemachin'
theme = 'gallery'
relativeURLs = false
canonifyURLs = false
publishDir = 'docs'
defaultContentLanguage = 'en'

[params]
  customCSS = ["css/custom.css"]

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    [languages.en.params]
      [languages.en.params.socialIcons]
        instagram = "https://instagram.com/chema.chin"
        github = "https://github.com/chemachin"
        email = "mailto:chemachin@gmail.com"
        linkedin = "https://www.linkedin.com/in/josé-maría-moreno-retamero-1211bb130/"
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "Home"
        url = "/"
        weight = 1
      [[languages.en.menu.main]]
        name = "Photography"
        url = "/photography/"
        weight = 2
      [[languages.en.menu.main]]
        name = "About"
        url = "/about/"
        weight = 3

  [languages.es]
    languageName = "Español"
    weight = 2
    [languages.es.params]
      [languages.es.params.socialIcons]
        instagram = "https://instagram.com/chema.chin"
        github = "https://github.com/chemachin"
        email = "mailto:chemachin@gmail.com"
        linkedin = "https://www.linkedin.com/in/josé-maría-moreno-retamero-1211bb130/"
    [languages.es.menu]
      [[languages.es.menu.main]]
        name = "Inicio"
        url = "/es/"
        weight = 1
      [[languages.es.menu.main]]
        name = "Galería"
        url = "/es/photography/"
        weight = 2
      [[languages.es.menu.main]]
        name = "Acerca de"
        url = "/es/about/"
        weight = 3